version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # đổi sang Dockerfile.gpu nếu muốn GPU
    image: thinh/traffic:latest
    working_dir: /app
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./datasets:/app/datasets
      - ./runs:/app/runs
      - ./data:/app/data  # Mount thư mục data để có file yaml
    command: >
      python train_traffic_signs.py
      --data data/traffic_signs_vietnam.yaml
      --epochs 100

# GPU mode:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.gpu
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]

